[theme]
name = "dracula"
[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#394b70"
idle_fg = "#c0caf5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#f7768e"
idle_fg = "#1f2335"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"
#format_swap = "{swap_used_percents}"
[block.theme_overrides]
idle_bg = "#e0af68"
idle_fg = "#1f2335"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#3d59a1"
idle_fg = "#c0caf5"

[[block]]
block = "nvidia_gpu"
label = "GTX 1060"
show_utilization = true
show_memory = true
show_temperature = true
interval = 1
[block.theme_overrides]
idle_bg = "#41a6b5"
idle_fg = "#1f2335"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#bb9af7"
idle_fg = "#1f2335"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
[block.theme_overrides]
idle_bg = "#24283b"
idle_fg = "#c0caf5" 

#[[block]]
#block = "battery"
#if_command = "test -e /sys/class/power_supply/BAT0"
