theme = "plain"
icons = "awesome6"
#icons_format=" <span font_family='NotoSans Nerd Font'>{icon}</span> "

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"
#format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
label = "GTX 1060"
show_utilization = true
show_memory = true
show_temperature = true
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

#[[block]]
#block = "battery"
#if_command = "test -e /sys/class/power_supply/BAT0"
