require('config.tokyonight')
require('options')
require('config.treesitter')
require('config.lsp')
require('config.lspsaga')
require('config.cmp')
require('config.nvimtree')
require('config.lualine')
require('config.dap')
require('config.dashboard')
require('config.null-ls')
-- require('which-key').setup()
require('keybindings')
